### ISSUE TITLE
Error on widget page

### ISSUE THREAD

**Issue by LudovicFauchet** [BeAPI/acf-svg-icon#11]
Hello,

When i'm on my widget pgae to add some widgets on my sidebar, i can't.

I have this in my console : `Cannot read property 'replace' of undefined`

And it's work when your plugin is disable.

Cheers

Thanks for your help

**Comment by MaximeCulea** [comment]
Hello @LudovicFauchet, 

Thank you for the request, we have to investigate. I think jquery "replace" is not present.

**Comment by LudovicFauchet** [comment]
Hello @MaximeCulea ,

Do you have any news about this issue ?

Cheers

**Comment by LudovicFauchet** [comment]
Hello @MaximeCulea ,

I'm back :p Did you find any solution for my issue ?

Cheers

**Comment by herewithme** [comment]
I do not reproduce on a fresh install of WP, ACF and our plugin.

Since the ticket is old, I close it.
