### ISSUE TITLE
Parse error: syntax error, unexpected 'version'

### ISSUE THREAD

**Issue by lucasjulian** [BeAPI/acf-svg-icon#16]
Hi ;) 

I encountered the folowing error when I upload an SVG (downloaded from flaticon.com) when I try to edit my ACF fields in the BO.

Parse error: syntax error, unexpected 'version' (T_STRING) in /app/public/wp-content/uploads/2019/10/idea.svg on line 1

My SVG start like below: 
![Capture](https://user-images.githubusercontent.com/13873559/67557819-18dd2c80-f716-11e9-84cf-c549a359e549.JPG)

Did I miss something ? It's strange because I success to add an SVG before, but not right now :(

**Comment by herewithme** [comment]
Probably fixed on these commit : https://github.com/BeAPI/acf-svg-icon/commit/f0fc1f5bbcbf3b39c4906a3bb1d29394b2408c85
