### ISSUE TITLE
Provide filter on parsed svg

### ISSUE THREAD

**Issue by jmau111** [BeAPI/acf-svg-icon#4]
Would be super cool to be able to filter icon/éléments. This way some elements could be hidden. For example:  I got a field for social networks and I just want social icons not the whole set of avg icons.

This filter could be placed where the the parse_svg () executes.

**Comment by 7studio** [comment]
Hi Julien,
If my PR is merged, you can do it via the filter `acf_svg_icon_data` :wink: See: https://github.com/BeAPI/acf-svg-icon/pull/2/commits/f4f8b11f873977a377bd0ba3f097d6f80bd9cc5b
